#include <stdio.h>
#include <signal.h>
#include <stdlib.h>

// EJEMPLO 1
/*
void manejador(int sig) {
	printf("Recibida señal %d!\n",sig);
}

int main() {

	// SIGINT interrumpe el proc (ctrl+c) Interactive attention signal. Generally generated by the application user.
	signal(SIGINT, manejador);
	printf("Esperando señal.\n");
	pause();
	printf("Saliendo.\n");
	return 0;
}
*/

/* PROGRAM OUTPUT
➜  c_programming_files git:(studying_t4) ✗ ./signal
	Esperando señal.
	^C (ctrl+c)
	Recibida señal 2!
	Saliendo.
*/

// FIN EJEMPLO 1



// EJEMPLO 2

int pid;

void manejador(int sig) {
	printf("Manejador - Entro en el manejador: \n");
	// Si pid == 0, significa que es un proceso hijo
	if(pid == 0){
		printf("Manejador -  IF PID == 0: \n");
		printf("Manejador - Hijo: Recibida señal %d\n", sig);
		printf("Manejador - PID es: %d\n", getppid());
		kill(getppid(), SIGUSR1);
		printf("Manejador - KILL \n");
		exit(0);
	} else {
		printf("Manejador -  IF PID != 0: \n");
		printf("Manejador - Padre: Recibida señal %d\n", sig);
	}
}

int main() {
	
	printf("MAIN - PID: %d\n", pid);
	printf("MAIN - SIGNAL ()\n");
	signal(SIGUSR1, manejador);
	printf("MAIN - Siguiente instrucción es el FORK\n");
	pid = fork();
	printf("MAIN - Tras el fork, PID es ahora: %d\n", pid);
	
	if ( pid == 0 ) { // HIJO
		while(1);
	}
	else { // Padre
		kill(pid, SIGUSR1);
		wait(NULL);
		printf("MAIN - El hijo terminó\n");
	}
	return 0;
}

/* PROGRAM OUTPUT


*/

// FIN EJEMPLO 2









/*
SIGNAL()

https://www.tutorialspoint.com/c_standard_library/c_function_signal.htm
The C library function void (*signal(int sig, void (*func)(int)))(int) sets a function to handle signal 
i.e. a signal handler with signal number sig.

void (*signal(int sig, void (*func)(int)))(int)
sig − This is the signal number to which a handling function is set. 
func − This is a pointer to a function. This can be a function defined by the programmer or one of the following predefined functions

This function returns the previous value of the signal handler, or SIG_ERR on error.


signal(int signum, sighandler_t handler)
asigna a la señal de número signum el manejador handler. El manejador puede ser:
	§ Una función a implementar void handler(int sig)
	§ Una acción a realizar como:
		• SIG_DFL: Acción por defecto de la señal
		• SIG_IGN: Ignora la señal

*/


